version: "3"

services:

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django
    container_name: django
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - 8000:8000
